apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: angular-app-template
  title: Example Angular Template
  description: An example template for the scaffolder that creates a simple Angular application
  tags:
    - angular
    - frontend
    - template
spec:
  owner: user:guest
  type: website
  path: /templates/angular-app-template
  parameters:
    - title: Project Name
      description: Enter the name of your Angular project
      required: true
    - title: Description
      description: Enter a short description of your Angular app
      required: true
  steps:
  - id: fetch
    name: Fetch Template Repository
    action: fetch:template
    input:
      url: https://github.com/your-repo/angular-template
      targetPath: .
  - id: write-files
    name: Write Multiple Files
    action: multi:action
    steps:
      - id: write-angular-json
        name: Write angular.json
        action: write:file
        input:
          path: angular.json
          content: |
            {
              "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
              "version": 1,
              "newProjectRoot": "projects"
            }
      - id: write-tsconfig
        name: Write tsconfig.json
        action: write:file
        input:
          path: tsconfig.json
          content: |
            {
              "extends": "./tsconfig.base.json",
              "compilerOptions": {
                "outDir": "./dist/out-tsc"
              }
            }
      - id: write-readme
        name: Write README.md
        action: write:file
        input:
          path: README.md
          content: |
            # Angular App
            This is a generated Angular application.
  - id: log
    name: Log Success
    action: debug:log
    input:
      message: "Successfully wrote all files!"

    - id: log
      name: Log Success
      action: debug:log
      input:
        message: "Angular app template successfully customized!"
